server:
  port: 8091
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # Git≤÷ø‚µÿ÷∑
          uri: https://github.com/pHraySc/spring-cloud-config-repo.git
          # Git≤÷ø‚’À∫≈
          username: pHraySc
          # Git≤÷ø‚√‹¬Î
          password: sc19951214syx